### ISSUE TITLE
Event list too long

### ISSUE THREAD

**Issue by herrbrixter** [epicarchitect/breakbadhabits#4]
I have around 25 events and the app is showing me all. I think showing the last 10 events suffice.

**Comment by epicarchitect** [comment]
@herrbrixter In the new version, I decided not to show this list under the calendar on the habit screen. I can do the same in the old version. Or maybe you still want to see a few recent events?

**Comment by herrbrixter** [comment]
I think the recent events are useful but just display a shorter list.

**Comment by epicarchitect** [comment]
Okay, then I'll make both the new and the old versions show the last 10 events for the current month.

**Comment by herrbrixter** [comment]
Great! Thanks

**Comment by herrbrixter** [comment]
Please show the last 10 events regardless of month. It's a good motivation
to see the last event was, for example, 2 months ago rather than not seeing
any event for the current month.

**Comment by epicarchitect** [comment]
Oh, and I already posted an update to the market 😅 Well, okay, I'll redo it, it's not difficult for me)

**Comment by herrbrixter** [comment]
Hahaha. Thanks again!

**Comment by epicarchitect** [comment]
The update is out!

**Comment by herrbrixter** [comment]
Ok, I will test it. Thanks

**Comment by herrbrixter** [comment]
The event list is just 10 entries now.
