### ISSUE TITLE
AM or PM should default to current time

### ISSUE THREAD

**Issue by herrbrixter** [epicarchitect/breakbadhabits#5]
When I pick the time, it defaults to the current hour and minute but the AM/PM is always AM.

**Comment by epicarchitect** [comment]
okey i will check

**Comment by epicarchitect** [comment]
it's a bug in the library I'm using to display this window. So I can't fix it :(

**Comment by herrbrixter** [comment]
Will it be fixed in the new version?

**Comment by epicarchitect** [comment]
Yes, I will have a self-written calendar and time selection

**Comment by herrbrixter** [comment]
Ok. We can close this ticket when you publish your new version.

**Comment by epicarchitect** [comment]
it should have been fixed in the new version, please check

**Comment by herrbrixter** [comment]
I'm not using the app anymore but you can close this if you think it's fixed. Thanks!
