### ISSUE TITLE
Incorrect abstinence chart heights

### ISSUE THREAD

**Issue by JacquesWust** [epicarchitect/breakbadhabits#9]
The abstinence chart seems to have incorrect heights. Please see attached screenshot where 7d, 8d and 7d 22h all have the same height.
<img src="https://github.com/user-attachments/assets/4abd1688-0708-4a44-a033-6e707c6342c8" alt="BadHabitsIssueScreenshot" width="300">

**Comment by epicarchitect** [comment]
Thank you for informing! Try updating to the latest version, it should have been fixed there

**Comment by JacquesWust** [comment]
Wow that was quick - thanks!
